Adding 3 Guides on advanced assets creation
PalworldModding/Docs pull request #5
Opened 2024-02-02 16:49 UTC by Dytser

Adding 3 guides
Material Slots, Character Customisation Sliders (shapekeys, likely will make one for heads etc), And Jiggle Physics/phys bones.

2024-02-02 18:44 UTC, localcc requested changes

2024-02-02 18:44 UTC, localcc commented on docs/asset-swapping/Advanced Asset Creation/Character Customisation Colors.md
> +Guide written by: Dytser
Maybe make the `Guide written by` thing bold, as well as the other line

2024-02-02 18:44 UTC, localcc commented on docs/asset-swapping/Advanced Asset Creation/Jiggle Physics.md
> +### exporting
Capitalize

2024-02-03 00:05 UTC, Dytser commented
All very good points, Ill sort those out.

2024-02-03 00:12 UTC, Dytser commented on docs/asset-swapping/Advanced Asset Creation/Jiggle Physics.md
> +### exporting
Fixed!

2024-02-03 00:13 UTC, Dytser commented on docs/asset-swapping/Advanced Asset Creation/Character Customisation Colors.md
> +Guide written by: Dytser
Sorted!
Did the same with the other two files!

2024-02-03 13:56 UTC, localcc approved these changes

2024-02-03 13:56 UTC, merged